# Generated by Django 4.2.4 on 2023-09-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_course_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Ordenes',
        ),
    ]
